### ISSUE TITLE
Config.AllowRacerCreationForAnyone not functional, God user not made on start up

### ISSUE THREAD

**Issue by alberttheprince** [Coffeelot/cw-racingapp#15]
Thought these might be small issues to create seperate issue reports but currently:

Config.AllowRacerCreationForAnyone does not actually allow race creation for anyone (racers cannot make races)

The first user is not assigned as god role when signing up the tablet (get assigned racer) and changing it via the DB does not reflect in game.

No f8 or server issues, used on Qbox.

**Comment by Coffeelot** [comment]
Fixed in latest patch. Will hopefully work you grab latest source.
Release coming later today. Patch notes will be posted in discord.

**Comment by Coffeelot** [comment]
Fixed in latest patch. Will hopefully work you grab latest source.
Release coming later today. Patch notes will be posted in discord.
