### ISSUE TITLE
Suggestion: Move Available to always be the main "view" of the tablet

### ISSUE THREAD

**Issue by alberttheprince** [Coffeelot/cw-racingapp#16]
Players are really enjoying the racing experience! They had some feedback, which was to move "Available" to the main page, as it makes viewing new races the main page for creators. 

We've set racers to have the ability to make races (I think something a lot of other users may do) and it would be good to have all current/available races viewable at first, making it easier to open and join

![image](https://github.com/user-attachments/assets/3be037f5-2fe3-47d9-83df-9b7aeec77d92)

**Comment by Coffeelot** [comment]
The plan is to merge available and current, as current will always just be one anyway it can be in the same list.

Not sure if that solves the problem?

Also, the Discord is alot better than github as I do tend to miss issues posted here, and it's a better platform for discussion and debugging issues.

**Comment by alberttheprince** [comment]
Yeah that solves it.

Sure, I'm just a fan of GitHub for documentation/tracking!
