### ISSUE TITLE
HUD not showing when resources restarted

### ISSUE THREAD

**Issue by Spenjunior** [Coffeelot/cw-racingapp#20]
TypeError: Cannot read properties of undefined (reading 'translations') (@cw-racingapp/html/dist/assets/index-dd5e76d8.js:1)
Hello sir, please help me When a race start I got this error above spamming all over console and the race hud not showing. this happened when I restart the resource cw-racingapp. I never experience this before but after I try to change the hud style it start to be like this. is this because of install npm into the server? I did the command in this https://github.com/alenvalek/fivem-vuejs-boilerplate/blob/main/README.md
![d](https://github.com/user-attachments/assets/89985289-c145-4952-a503-f2c74e8eb884)

**Comment by Coffeelot** [comment]
Did you change the translation in the Config to something that does not exist?

Also, changing the UI is not something we provide support on as it's mainly a node/npm thing and any issues from it is user error not related to Racingapp itself.

**Comment by Coffeelot** [comment]
Closing ticket as no response.
