### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by Trollan** [Coffeelot/cw-racingapp#6]
Hello, first of all I love your scripts and the work you do, in this case I wanted to comment on a bug that was impossible to see on the test server because it does not happen with 2 or 3 clients in the race, but on the main server When approximately 8 clients go to a race, when you start the race you crash all those who were participating. If you want to see it, I can try to make a video with the logs in case you are interested since I saw that you keep this project active.

**Comment by Coffeelot** [comment]
1. Does it crash instantly on race start? 
2. Does it crash on all setup settings?
3. Did you change anything in the config?
4. Any crash logs?

A video could help, but client logs (with debug enabled) would be better. This will be impossible to debug for me but I'll try to see if I can spot anything that would cause this.

**Comment by Coffeelot** [comment]
Also, does it crash on all tracks? I know before someone had an issue with it crashing when a track had to many checkpoints for example.

**Comment by Trollan** [comment]
No, it is not on all the tracks, the users in charge of the illegal races on my server did many races, some with more than 500 points that worked and other smaller ones with 100 that did not, however I think it failed depending on the route.

**Comment by Coffeelot** [comment]
Ah. Yeah it crashes cause you're asking GTA to spawn in Checkpoints * 2 entities. 

100-500 checkpoints is kinda insane if you think about it like that haha. So yeah, can't really support that. 
Thought I added a notification when creating to many checkpoints but guess I forgot
