### ISSUE TITLE
race positions at end

### ISSUE THREAD

**Issue by SmithyDevelopment** [Coffeelot/cw-racingapp#8]
Hi, I am not able to see the finishing positions of the race, only fastest lap times..

**Comment by Coffeelot** [comment]
No error messages?

**Comment by Coffeelot** [comment]
Haven't heard of anyone else reporting this error. 
I suggest you try to reinstall the script, and go over the config.

**Comment by SmithyDevelopment** [comment]
I see you just updated it, im still on the master/basic tablets, I will give the new one a go! Looks Great! Many thanks
